export default{
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    GHANGE_QTY:"GHANGE_QTY",
    INCREASE_ORDER:'INCREASE_ORDER',
    DECREASE_ORDER:'INCREASE_ORDER',
    CLEAR_CART:'CLEAR_CART',
}